services:
  - type: web
    name: productlogik-backend
    env: python
    region: frankfurt # Optional: Choose your region
    plan: free # Optional: free, starter, etc.
    buildCommand: pip install -r requirements.txt
    # Switched to uvicorn directly for better logging and less complexity
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
