services:
  - type: web
    name: productlogik-backend
    env: python
    region: frankfurt # Optional: Choose your region
    plan: free # Optional: free, starter, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
